<?php

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Request;

class Shop extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $gid = $this->request->get();
        var_dump($gid);
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        $uid = $this->request->id;
        //用户id
        $data = $this->request->post();//获取数据
        $gid = $data['gid'];
        $nprice = $data['price'];
        $model = model('Cartmodel');
        $extramodel = model('Cartextramodel');
        $goodsInfo = $extramodel->queryone(['uid' => $uid, 'gid' => $gid]);
        $IncRes = '';
        if ($goodsInfo['num'] > 1) {
            $IncRes = $extramodel->goodsNumDec(['uid' => $uid, 'gid' => $gid]);
        } else {
            $insertRes = $extramodel->deleteGoods(['uid' => $uid, 'gid' => $gid]);
        }
        $numInc = $model->cartDec($uid, 'total');
        $priceInc = $model->cartDec($uid, 'price', $nprice);
        if (($IncRes && $numInc && $priceInc) || ($insertRes && $numInc && $priceInc)) {
            Db::commit();
            return json([
                'code' => config('code.success'),
                'msg' => '购物车减少成功'
            ]);
        } else {
            Db::rollback();
            return json([
                'code' => config('code.fail'),
                'msg' => '购物车减少失败'
            ]);
        }
    }

    /**
     * 显示指定的资源
     *
     * @param  int $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request $request
     * @param  int $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
